#include "param_log.h"
#include <ft_printf.h>
#include <macros.h>
#include <sys/ptrace.h>

static const flag_str_t ptrace_requests[] = {
	FLAG_STR(PTRACE_TRACEME),
	FLAG_STR(PTRACE_PEEKTEXT),
	FLAG_STR(PTRACE_PEEKDATA),
	FLAG_STR(PTRACE_PEEKUSER),
	FLAG_STR(PTRACE_POKETEXT),
	FLAG_STR(PTRACE_POKEDATA),
	FLAG_STR(PTRACE_POKEUSER),
	FLAG_STR(PTRACE_CONT),
	FLAG_STR(PTRACE_KILL),
	FLAG_STR(PTRACE_SINGLESTEP),
	FLAG_STR(PTRACE_GETREGS),
	FLAG_STR(PTRACE_SETREGS),
	FLAG_STR(PTRACE_GETFPREGS),
	FLAG_STR(PTRACE_SETFPREGS),
	FLAG_STR(PTRACE_ATTACH),
	FLAG_STR(PTRACE_DETACH),
	FLAG_STR(PTRACE_GETFPXREGS),
	FLAG_STR(PTRACE_SETFPXREGS),
	FLAG_STR(PTRACE_SYSCALL),
	FLAG_STR(PTRACE_SETOPTIONS),
	FLAG_STR(PTRACE_GETEVENTMSG),
	FLAG_STR(PTRACE_GETSIGINFO),
	FLAG_STR(PTRACE_SETSIGINFO),
	FLAG_STR(PTRACE_GETREGSET),
	FLAG_STR(PTRACE_SETREGSET),
	FLAG_STR(PTRACE_SEIZE),
	FLAG_STR(PTRACE_INTERRUPT),
	FLAG_STR(PTRACE_LISTEN),
	FLAG_STR(PTRACE_PEEKSIGINFO),
	FLAG_STR(PTRACE_GETSIGMASK),
	FLAG_STR(PTRACE_SETSIGMASK),
	FLAG_STR(PTRACE_SECCOMP_GET_FILTER),
	FLAG_STR(PTRACE_SECCOMP_GET_METADATA),
	FLAG_STR(PTRACE_GET_SYSCALL_INFO),
};

/**
 * @brief Log ptrace request
 *
 * @param value the value to log
 * @return int the number of bytes written
 */
int log_PTRACE_REQUEST(uint64_t value)
{
	return option_log(value, ptrace_requests, ELEM_COUNT(ptrace_requests), "PTRACE_???");
}