#include "param_log.h"
#include <ft_printf.h>
#include <macros.h>
#include <signal.h>
#include <time.h>

static const flag_str_t clockid_values[] = {
	FLAG_STR(CLOCK_REALTIME),
	FLAG_STR(CLOCK_MONOTONIC),
	FLAG_STR(CLOCK_PROCESS_CPUTIME_ID),
	FLAG_STR(CLOCK_THREAD_CPUTIME_ID),
	FLAG_STR(CLOCK_MONOTONIC_RAW),
	FLAG_STR(CLOCK_REALTIME_COARSE),
	FLAG_STR(CLOCK_MONOTONIC_COARSE),
	FLAG_STR(CLOCK_BOOTTIME),
	FLAG_STR(CLOCK_REALTIME_ALARM),
	FLAG_STR(CLOCK_BOOTTIME_ALARM),
	FLAG_STR(CLOCK_TAI),
	FLAG_STR(CLOCK_PROCESS_CPUTIME_ID),
	FLAG_STR(CLOCK_THREAD_CPUTIME_ID),
	FLAG_STR(CLOCK_MONOTONIC_RAW),
	FLAG_STR(CLOCK_REALTIME_COARSE),
	FLAG_STR(CLOCK_MONOTONIC_COARSE),
	FLAG_STR(CLOCK_BOOTTIME),
	FLAG_STR(CLOCK_REALTIME_ALARM),
	FLAG_STR(CLOCK_BOOTTIME_ALARM),
	FLAG_STR(CLOCK_TAI),
};

int log_CLOCKID_T(uint64_t value)
{
	return option_log(value, clockid_values, ELEM_COUNT(clockid_values), "CLOCK_???");
}